name: Nomad Validate
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.nomad.hcl"

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
      nomad: ${{ steps.changes.outputs.nomad }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: Get Changed Files
        id: changes
        # Set outputs
        run: |
          echo "NOMAD_FILES_CHANGED=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .nomad | xargs) >> $GITHUB_OUTPUT"

  nomad-plan:
    needs: changedfiles
    env:
      NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
    runs-on: ubuntu-26.04
    steps:
      - name: check
        run: echo "${{ steps.changes.outputs.NOMAD_FILES_CHANGED }}"
      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_KEY }}
          tags: tag:ci
          version: 1.58.2
      - name: check connectivity
        run: ifconfig ; host sense.orca-ordinal.ts.net
      - name: Checkout change
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Add Dev Env
        uses: jdx/mise-action@v5
        with:
          install: true
      - name: Plan the job
        run: for file in ${{ steps.changes.outputs.nomad }} ; do nomad plan ${file} ; done
